
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp001
  name: myapp001
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 80
  selector:
    app: myapp001
  type: NodePort

