apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp001
  name: myapp001
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 80
  selector:
    app: myapp001
  type: LoadBalancer